spring:
  application:
    name: KafkaAxonExample

axon:
  kafka:
    clientid: kafka-axon-example
    defaulttopic: local.event
    producer:
      retries: 0
      bootstrapservers: localhost:9092
    consumer:
      group-id: "local.event.consumer-group"

    properties:
      security.protocol: PLAINTEXT
